"""Add AudioProcessingTask model

Revision ID: 9c2e0c502796
Revises:
Create Date: 2026-01-30 14:24:56.754203

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c2e0c502796"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_processing_tasks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "STARTED", "SUCCESS", "FAILURE", name="taskstatusenum"), nullable=False),
        sa.Column("audio_file_key", sa.String(), nullable=False),
        sa.Column("ai_response", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audio_processing_tasks_id"), "audio_processing_tasks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audio_processing_tasks_id"), table_name="audio_processing_tasks")
    op.drop_table("audio_processing_tasks")
    # ### end Alembic commands ###
